project:
  group: laplacian
  name: project.project-types
  type: model
  namespace: laplacian
  version: '1.0.0'
  description:
    en: |
      The basic project types used in the Laplacian project.
    ja: |
      The basic project types used in the Laplacian project.
    zh: |
      The basic project types used in the Laplacian project.
  source_repository:
    url: https://github.com/nabla-squared/laplacian.project.project-types.git
    branch: master
  module_repositories:
    local:
      path: ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  plugins:
  - group: laplacian
    name: project.schema-plugin
    version: '1.0.0'
  model_files:
  - 'src/'
