project:
  group: laplacian
  name: project.project-types
  type: model
  namespace: laplacian
  version: '1.0.0'
  description:
    en: |
      The model data that defines the content of each project type.
    ja: |
      各プロジェクトタイプの内容を定義するモデルデータです。
    zh: |
      定义了每个项目类型的内容的模型数据。
  source_repository:
    url: https://github.com/nabla-squared/laplacian.project.project-types.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  model_files:
  - 'dest/'
